version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: Healthcare.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - ConnectionStrings__Default=Server=sqlserver;Database=HealthcareDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
      - rabbitmq

  noteconsumer:
    build:
      context: .
      dockerfile: Healthcare.NoteConsumer/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ConnectionStrings__Default=Server=sqlserver;Database=HealthcareDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
      - rabbitmq

volumes:
  sql_data:
